/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ExcelTableService } from "../excelTable.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExcelTableCreateInput } from "./ExcelTableCreateInput";
import { ExcelTable } from "./ExcelTable";
import { ExcelTableFindManyArgs } from "./ExcelTableFindManyArgs";
import { ExcelTableWhereUniqueInput } from "./ExcelTableWhereUniqueInput";
import { ExcelTableUpdateInput } from "./ExcelTableUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ExcelTableControllerBase {
  constructor(
    protected readonly service: ExcelTableService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ExcelTable })
  @nestAccessControl.UseRoles({
    resource: "ExcelTable",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createExcelTable(
    @common.Body() data: ExcelTableCreateInput
  ): Promise<ExcelTable> {
    return await this.service.createExcelTable({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        tableName: true,
        data: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ExcelTable] })
  @ApiNestedQuery(ExcelTableFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ExcelTable",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async excelTables(@common.Req() request: Request): Promise<ExcelTable[]> {
    const args = plainToClass(ExcelTableFindManyArgs, request.query);
    return this.service.excelTables({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        tableName: true,
        data: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ExcelTable })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExcelTable",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async excelTable(
    @common.Param() params: ExcelTableWhereUniqueInput
  ): Promise<ExcelTable | null> {
    const result = await this.service.excelTable({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        tableName: true,
        data: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ExcelTable })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExcelTable",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateExcelTable(
    @common.Param() params: ExcelTableWhereUniqueInput,
    @common.Body() data: ExcelTableUpdateInput
  ): Promise<ExcelTable | null> {
    try {
      return await this.service.updateExcelTable({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          tableName: true,
          data: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ExcelTable })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExcelTable",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteExcelTable(
    @common.Param() params: ExcelTableWhereUniqueInput
  ): Promise<ExcelTable | null> {
    try {
      return await this.service.deleteExcelTable({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          tableName: true,
          data: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
